services:
  db:
    image: postgres:16
    container_name: notifier-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rober0xf -d notifier -p 5432"]
      interval: 2s
      timeout: 5s
      retries: 10

  backend:
    build: ./
    image: notifier-backend:0.1
    container_name: notifier-back
    env_file:
      - ./.env
    environment:
      MIGRATIONS_PATH: file:///sql/migrations
    depends_on:
      - db
    volumes:
      - ./sql/migrations:/sql/migrations

  frontend:
    build: ../notifier-front
    image: notifier-frontend:0.1
    ports:
      - "8080:80"
    container_name: notifier-front
    depends_on:
      - backend

volumes:
  postgres_data:
